[project]
name = "sea-battle-24-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.10",
    "numpy>=2.4.2",
    "ursina>=8.3.0",
]
